/*
 * This source file was generated by the Gradle 'init' task

 */

package org.example;
import java.io.IOException;
import java.util.*;

import org.example.entities.Ticket;
import org.example.entities.user;
import org.example.services.Trainservices;
import org.example.services.UserBookingService;
import org.example.utils.userutilservice;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner scn = new Scanner(System.in);
        System.out.println("wELCOME TO THE TIKET BOOKING SERVICE!!");
        System.out.println();
        System.out.println();
        int Option =0;
    
   
       UserBookingService userentered;
       Trainservices trainservice;
       try {
    userentered = new UserBookingService();
    trainservice= new Trainservices();
} catch (IOException e) {
    e.printStackTrace(); // ← change back to this
    return;
}

        while(Option!=7){
        System.out.println("Choose one of the following to proceed");
        System.out.println("Press 1 to Signup");
        System.out.println("Press 2 to Login");
        System.out.println("Press 3 to View Bookings");
        System.out.println("Press 4 to Search Train");
        System.out.println("Press 5 to Book ticket");
        System.out.println("Press 6 to Cancel ticket");
        System.out.println("Press 7 to EXIT");
        
        Option = scn.nextInt();
        switch (Option) {
            case 1:
                System.out.println("Enter Name");
                String newname = scn.next();
                System.out.println("Enter Password");
                String newpassword = scn.next();
                user newuser = new user(newname , newpassword,userutilservice.gethashpass(newpassword), new ArrayList<Ticket>(), UUID.randomUUID().toString() );
                if(userentered!=null){
                    userentered.signup(newuser);
                }
                else{
                    System.out.println("User booking not available");
                }
               
                break;
        
            case 2:
                if(userentered!=null){
                System.out.println("Enter your name:");
                String username = scn.next();
                System.out.println("Enter you passowrd");
                String userpassword = scn.next();
                userentered.returnuser(username,userpassword);
                boolean loggedStatus = userentered.userlogin();
                userentered.setloggedstatus(loggedStatus);
                if(loggedStatus==true){
                System.out.println("Successfully logged in");
                }
                else{
                    System.out.println("Wrong credentials, user not found. Please try again");
                }}
                else{
                    System.out.println("Error in login , try again");
                }
                break;
            case 3:
                if(userentered.getloggedstatus()){
                userentered.fetchticket();
                }
                  break;
            case 4:
                scn.nextLine();
                System.out.println("Enter the Source Station");
                String source = scn.nextLine();
                System.out.println("Enter the destination Station");
                String destination = scn.nextLine();
        
                try{
                trainservice.seleted_trains(source, destination, scn);
                 }
                catch(IOException e){
                e.printStackTrace();
                 }
                break;
            
            case 5:
               userentered.bookticket(trainservice, scn);
                break;
            
            case 6:
                System.out.println("Enter the ticket id: ");
                String Ticket_id = scn.next();
                try{
                userentered.Cancelticket(Ticket_id);
                }
                catch(IOException e){
                e.printStackTrace();
                }
                break;
            case 7:
                Option = 7;
                
        }

        }

        


    }
}
